// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjtfKFk3YOSNQ12pwa2WOPZKG28ZOsFJw',
    appId: '1:70416891040:web:810cf7c6c8e33d7620ddc5',
    messagingSenderId: '70416891040',
    projectId: 'findoc-financial',
    authDomain: 'findoc-financial.firebaseapp.com',
    storageBucket: 'findoc-financial.firebasestorage.app',
    measurementId: 'G-3LZ2CB8GNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApm8iIH66Vz1nvybUbdVuwNTOrqCF3zP4',
    appId: '1:70416891040:android:28533c81c4fa8a2f20ddc5',
    messagingSenderId: '70416891040',
    projectId: 'findoc-financial',
    storageBucket: 'findoc-financial.firebasestorage.app',
  );
}
